// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsy-wgawIw6tDAbw-efaWXT3gyAxEBUDo',
    appId: '1:229137297335:web:ba90b4e102b364ee014232',
    messagingSenderId: '229137297335',
    projectId: 'crypto-cent',
    authDomain: 'crypto-cent.firebaseapp.com',
    storageBucket: 'crypto-cent.appspot.com',
    measurementId: 'G-ZVZZSB2SRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkVAK5Kr4U-e3ylCG3rIuMqACle_BfkPg',
    appId: '1:229137297335:android:eda1ca79bb89ccaa014232',
    messagingSenderId: '229137297335',
    projectId: 'crypto-cent',
    storageBucket: 'crypto-cent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4z53cZ6RpIGQKMDx7l-GMu_ie9BV5Krk',
    appId: '1:229137297335:ios:c8f8140190512f43014232',
    messagingSenderId: '229137297335',
    projectId: 'crypto-cent',
    storageBucket: 'crypto-cent.appspot.com',
    iosClientId: '229137297335-prg1amdhikgqm4srpn66c9ja0uh5gl1l.apps.googleusercontent.com',
    iosBundleId: 'com.devmarkaz.cryptoCent',
  );
}
