// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72sLLR4LGlQQ8Hsrl6ei0u0FS5dZbFwE',
    appId: '1:68990521985:web:0f1539d06252f92c84b380',
    messagingSenderId: '68990521985',
    projectId: 'charpaiproject',
    authDomain: 'charpaiproject.firebaseapp.com',
    storageBucket: 'charpaiproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_nHgFLpURgrnUOgkxH2_jB6Z6IXSSP8s',
    appId: '1:68990521985:android:6950ec28ef068eba84b380',
    messagingSenderId: '68990521985',
    projectId: 'charpaiproject',
    storageBucket: 'charpaiproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1b7t3Tbbao3ubDJZlSghkPz3krYRMXNs',
    appId: '1:68990521985:ios:f3195227c527ef0984b380',
    messagingSenderId: '68990521985',
    projectId: 'charpaiproject',
    storageBucket: 'charpaiproject.appspot.com',
    iosClientId: '68990521985-vepslfv151isikll7imj3jmqj5obi57n.apps.googleusercontent.com',
    iosBundleId: 'com.example.charpi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1b7t3Tbbao3ubDJZlSghkPz3krYRMXNs',
    appId: '1:68990521985:ios:f3195227c527ef0984b380',
    messagingSenderId: '68990521985',
    projectId: 'charpaiproject',
    storageBucket: 'charpaiproject.appspot.com',
    iosClientId: '68990521985-vepslfv151isikll7imj3jmqj5obi57n.apps.googleusercontent.com',
    iosBundleId: 'com.example.charpi',
  );
}
